import '../styles/globals.css'
import { SessionProvider } from "next-auth/react"
import { RecoilRoot } from 'recoil'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import TopNav from '../components/TopNav'
import SubNav from '../components/SubNav'

function MyApp({ Component, pageProps: { session, ...pageProps } }) {
  const localStoragePath = "amazon2.0-theme";
  const [dark, setdark] = useState();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      if (!localStorage.getItem(localStoragePath)) {
        if (window.matchMedia("(prefers-color-scheme: dark)").matches)
          localStorage.setItem(localStoragePath, "dark");
        else
          localStorage.setItem(localStoragePath, "light");
      }
      setdark(localStorage.getItem(localStoragePath))
    }
  }, []);

  return (
    <RecoilRoot>
      <SessionProvider session={session}>
        <div className={`${dark} overflow-hidden h-screen`}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          {/* Navigation */}
          <TopNav value={dark} handler={setdark} />
          <SubNav />
          <Component {...pageProps} />
        </div>
      </SessionProvider>
    </RecoilRoot>
  );
}

export default MyApp