import Head from 'next/head'
import TopNav from '../components/TopNav'
import SubNav from '../components/SubNav'
import Slider from '../components/Slider'
import CardsLine from '../components/CardsLine'
import Footer from '../components/Footer'
import { useEffect, useState } from 'react'

export default function Home() {
  const localStoragePath = "amazon2.0-theme";
  const [dark, setdark] = useState();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      if (!localStorage.getItem(localStoragePath)) {
        if (window.matchMedia("(prefers-color-scheme: dark)").matches)
          localStorage.setItem(localStoragePath, "dark");
        else
          localStorage.setItem(localStoragePath, "light");
      }
      setdark(localStorage.getItem(localStoragePath))
    }
  }, []);

  return (
    <div className={`${dark} overflow-hidden h-screen`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navigation */}
      <TopNav value={dark} handler={setdark} />
      <SubNav />
      {/* <3 */}
      {/* Main page */}
      <div id="scrollable" className="flex flex-col flex-1 h-screen overflow-y-scroll scrollbar-thumb-slate-400 hover:scrollbar-thumb-slate-500 scrollbar-thin scrollbar-thumb-rounded-full scrollbar-track-rounded-full mt-[104px] pb-[104px]">
        <div className="bg-emerald-100 dark:bg-[#111827] mx-0 p-0">
          <CardsLine />
          <CardsLine />
          <Slider />
          <Slider />
          <CardsLine />
        </div>

        {/* Footer */}
        <Footer />
      </div>
    </div>
  )
}
